### ISSUE TITLE
SlickInject <3

### ISSUE THREAD

**Issue by LegitSoulja** [LegitSoulja/SlickInject#1]
---
> ###### This issue is open for future support, recommendations, and bugs.
---

**Comment by LegitSoulja** [comment]
@Andrews54757 What do you think about this?

**Comment by LegitSoulja** [comment]
I can agree, things are very very messy. I think I'll finish this up tomorrow.

**Comment by Andrews54757** [comment]
Cool

**Comment by LegitSoulja** [comment]
@Andrews54757 You'll start seeing things coming together soon, as of that plugin I couldn't compile. Have you figured out my issue with requiring a file? 

Anyways,

I'll be allowing plugin devs to register new tables, and have the ability to set and receive data via MySQLi/SlickInject. 

Our Live.ogarul system will also be re-wrote, and replaced over at api.opnagar.

Changes should take effect this week?

**Comment by LegitSoulja** [comment]
@Andrews54757 Also, the domain of ogarul.io is up for renewal next month. Since we don't own anything called ogarul, should we let it go?

**Comment by LegitSoulja** [comment]
Haha not next month, this month I meant.

**Comment by Andrews54757** [comment]
Yes, you can let the domain go. Bye bye OgarUL. Also, be sure to put a notice up on the web

**Comment by LegitSoulja** [comment]
@Andrews54757 sounds good.

**Comment by LegitSoulja** [comment]
@Andrews54757 oops, just checked up on the domain, and the renewal isn't until next month, I thought it was this month, because this month is normally when I start renewing stuff..

Anyways, May 30, 2017 is the day the domain will be expired.

**Comment by LegitSoulja** [comment]
@Andrews54757 I've started to migrate Live, to the new API. You'll like the concept when you see it :),

but I need to know which of this stuff you are using, or not using. Because I have to re-write most of it to work with the site, safely "Say so". Some of this stuff im not accepting, due to the major GET access, that can destroy/delete databases with ease.

It'll be best, to for example make a site/dashboard to do those things with your needs, with some sort of key, or auth. I can do that if needed, but all GET requests are being removed because it will now be public, (Not the Data side), but the actual domain, it will have some public api's, as of a server list, and back end strict auth with plugin developer api's etc. 

If you don't understand anything with the Migration, and the new API, just DM my gitter.

**Comment by LegitSoulja** [comment]
The system of the API is based off of this, "SlickInject".

**Comment by Andrews54757** [comment]
Okay. Right now however, I am taking a long break. Also, moving to api will mean I will have to change OA's client and key system. I will do so later. Another thing though, is that the GET protocol is necessary for the key system, nodejs side.

**Comment by Andrews54757** [comment]
Or, we could just remove the key system. :)

**Comment by LegitSoulja** [comment]
@Andrews54757 

How and why is the get protocol needed for nodejs? You've fixed it with minirequest as I recall.

And no, we don't have to change the client, nor server side until the domain close which is on the 30th of May, but right now I am converting this system.

**Comment by LegitSoulja** [comment]
How about this, For all the calls you made, I'll make you a little nice panel, maybe implement it on the opnagar login site, to manage whatever. Maybe ability to execute SQL. We'll see. Depends on if I feel like re-writing all of this lol. I finished OAStats atleast, views, and Error reports. Haven't checked the others yet...

**Comment by Andrews54757** [comment]
@LegitSoulja Get is faster and more reliable then post. Even though post is more "secure".

**Comment by LegitSoulja** [comment]
@Andrews54757 It's pretty fast, for me Atleast.

**Comment by LegitSoulja** [comment]
@Andrews54757 if you want fast, we can move everything to a vps, (sites), and even start hosting.
