### ISSUE TITLE
notice error: Trying to get property of non-object in build/SlickInject.php on line 156

### ISSUE THREAD

**Issue by gabrielschuck** [LegitSoulja/SlickInject#11]
I'm getting this error when inserting with slickinject in a database table. The data is inserted, but the error occurs in the same way. I know it's easy to solve this, but could you please take a look?  Thanks!

**Comment by LegitSoulja** [comment]
@gabrielschuck Sorry, it needs updating. Also what version of PHP are you running?

**Comment by LegitSoulja** [comment]
Updated. Should now be working. 

I am however not using the 1 build file, and everything is working fine on my server php v5.6 > v7.1 tested.

**Comment by gabrielschuck** [comment]
I am using xampp with php 5.6.30.
I've updated now and am getting other errors:
Warning: mysqli::stmt_init(): Couldn't fetch mysqli in C:\xampp\htdocs\agenda\build\SlickInject.php on line 308

Fatal error: Call to a member function prepare() on null in C:\xampp\htdocs\agenda\build\SlickInject.php on line 309

**Comment by LegitSoulja** [comment]
@gabrielschuck hm, interesting. 1 sec

**Comment by LegitSoulja** [comment]
@gabrielschuck Can I get an example of usage? Ignore your credentials.

**Comment by LegitSoulja** [comment]
Running this, will let you know.
```php
if (!extension_loaded('mysqlnd')) die("mysqlind extension is not loaded.");
```

**Comment by gabrielschuck** [comment]
I have discovered that I am having two errors. The first, even with the Update, still continues.
The second of the previous comment is happening when I use the object As global within a function.
See the two codes below:


<?php
require ("config.php");
require (__DIR__."/build/SlickInject.php");
$sql=new SlickInject(server,username,password,database);
$sql->insert ("test",array("name"=>"Gabriel Schuck","city"=>"Novo hamburgo"));
$sql->close();
?>
It works fine, but I continue with the error of before:

Notice :  Trying to get property of non-object in C:\xampp\htdocs\agenda\build\SlickInject.php on line 156


Now the same code inside a function:

<?php
require ("config.php");
require (__DIR__."/build/SlickInject.php");
$sql=new SlickInject(server,username,password,database);

function test(){
global $sql;
$sql->insert ("test",array("name"=>"Gabriel Schuck","city"=>"Novo hamburgo"));
}
$sql->close();

test();
?>

Result:

Warning :  mysqli::stmt_init(): Couldn't fetch mysqli in
C:\xampp\htdocs\agenda\build\SlickInject.php on line 308

Fatal error :  Call to a member function prepare() on null in
C:\xampp\htdocs\agenda\build\SlickInject.php on line 309

Am I doing something wrong?

**Comment by LegitSoulja** [comment]
@gabrielschuck hm, let's try 2 things.

**Comment by LegitSoulja** [comment]
Re-update. Hopefully that fixes your issue. Even this worked. No error, nor warnings.

**Comment by gabrielschuck** [comment]
Thank you! Everything working now. One more little thing: Is it possible to use the limit gulle? How would it be?

**Comment by LegitSoulja** [comment]
@gabrielschuck 

SELECT([], "table", array("id"=>1, "LIMIT 1"));
> SELECT * FROM table WHERE id = 1 LIMIT 1

SELECT([], "table", array("LIMIT 1"));
> SELECT * FROM table LIMIT 1

Note, that if you use LIMIT, or anything as to that. It's your job to handle the use. For example, you cannot do

SELECT([], "table", array("LIMIT 1", "id"=>1));

**Comment by LegitSoulja** [comment]
Also, to send raw sql is complicating, but this is simple to execute, but it's something like this

```php
$row = (SlickInject)->getSQLObject("SELECT * FROM table LIMIT 1", null);

// WHERE example
$row = (SlickInject)->getSQLObject("SELECT * FROM table WHERE id = ? LIMIT 1", array("i", 1));
```
