### ISSUE TITLE
Latest

### ISSUE THREAD

**Issue by LegitSoulja** [LegitSoulja/SlickInject#2]
---
> ###### This issue is open for future support, recommendations, and bugs.
---

**Comment by systemroot** [comment]
> HAS NOT YET BEEN RELEASED!.

so is this ready for usage?

**Comment by LegitSoulja** [comment]
@systemroot yes, but it's up to you how you use it.

It's not fully fully finished, but it work for what the doc shows/and the test. Fell free to submit PR's.

**Comment by LegitSoulja** [comment]
@systemroot please push recent update/changes I've made.

**Comment by LegitSoulja** [comment]
@systemroot in a few days or now, i'll release the full version.

**Comment by systemroot** [comment]
okay.

ps i haven't test it yet. after that i'll if i can submit a PR or something..

**Comment by LegitSoulja** [comment]
@systemroot Just a curious question. What will you be using this for?

**Comment by LegitSoulja** [comment]
And if you would like to help in this project, the main work that needs to be done is the parser 

https://github.com/LegitSoulja/SlickInject/blob/dev/lib/Parser.php

btw, I will be working in the dev branch for now until a stable release.

**Comment by systemroot** [comment]
> Just a curious question. What will you be using this for?
first thing https://github.com/systemroot/botneted 
botnet'ed is a project who manages multiple vps. example you have 10 vps you install botneted somewhere add them all on it, and you can reboot all them from panel. you can get stats about space ram cpu etc. and you can send ex
"apt-get update" in all vps who you select from botneted panel :p

**Comment by LegitSoulja** [comment]
@systemroot do you know what SlickInject is used for? How is mysqli is needed with this?

**Comment by systemroot** [comment]
because my project will use mysql. to send get or delete data.
i can't create my project without mysql. 

example there will be a cron job who push vps informations from vps to botneted (mysql) and then SlickInject will be used as a class to show suff which is on database. because my project can't be done in real time. php can fail and dab error 500 server web panel is goes down..

**Comment by LegitSoulja** [comment]
@systemroot problems? There's non.

SlickInject illuminates duplicate code with sending, getting, deleting data from your database. SlickInject is also fast, and efficient.

Not only that, SlickInject can help prevent SQL Injections. Currently' SlickInject is only supported for MySQLI because I stopped working with  MySQL, and PDO, etc.

**Comment by LegitSoulja** [comment]
SQLObject can also be used stand-alone, if you're not interested in the SlickInject portion.

I updated SQLObject, and the docs for it https://github.com/LegitSoulja/SlickInject/blob/dev/README.md

**Comment by systemroot** [comment]
nice

**Comment by LegitSoulja** [comment]
@systemroot @Andrews54757 Finally done. 

Dev Branch : https://github.com/LegitSoulja/SlickInject/tree/dev
Example : https://github.com/LegitSoulja/SlickInject/blob/dev/test.php

Update poll : https://github.com/LegitSoulja/SlickInject/pull/3

Merging, and updating readme soon. Let me know of any bugs, as it has not been fully tested as of what is now released. Thanks. Enjoy SlickInject!.

**Comment by LegitSoulja** [comment]
Btw, any new names to call this project?

**Comment by systemroot** [comment]
SlickInject sounds good for me

**Comment by systemroot** [comment]
@LegitSoulja i'm doing something wrong or '11' is normal as output?
you can see it here
```http://api.botneted.com/update.php?token=1&name=the&lastname=raw```

**Comment by LegitSoulja** [comment]
@systemroot I don't see what you're seeing.

**Comment by systemroot** [comment]
:confused: 
![](http://i.imgur.com/C6YTxQ6.png)

**Comment by LegitSoulja** [comment]
@systemroot oh ok now I see. Can you provide some code? What are you doing exactly?

**Comment by systemroot** [comment]
a simple test

```php
<?php
namespace test;
function _load_all($a)
{
    foreach (glob($a) as $b) {
        if (is_dir($b)) {
            _load_all($b . "/*"); // recursive include.
            continue;
        } else {
            if (basename($b, ".php") == basename(__FILE__, ".php"))
                continue;

            if (pathinfo($b)['extension'] == "php") 
                include $b;
        }
    }
}
_load_all("lib/*");

use SlickInject\SlickInject as SlickInject;

// Get info
$id=$_GET['token'];
$name=$_GET['name'];
$lastname=$_GET['lastname'];

// create a new SlickInject instance
$_slickinject = new SlickInject();

// connect to the database
$_slickinject->connect("localhost", "user", "passwd", "db");

// update
$_slickinject->UPDATE('vms', array("name"=>"$name"), array("id"=>1));
$_slickinject->UPDATE('vms', array("lastname"=>"$lastname"), array("id"=>1));

$sql->close(); 
?>
```

**Comment by LegitSoulja** [comment]
@systemroot in Parser/SQLObject remove any echo's or print_r's. Guess I didn't remove them all.

**Comment by LegitSoulja** [comment]
Also, new SlickInject() can take the connect params.

**Comment by LegitSoulja** [comment]
And also, I've made a few changes some hours ago. Update doesn't work.

**Comment by LegitSoulja** [comment]
And no quotes are needed when added variables to an array.

**Comment by systemroot** [comment]
found it https://github.com/LegitSoulja/SlickInject/blob/dev/lib/SQLObject.php#L74

**Comment by LegitSoulja** [comment]
@systemroot thanks.

**Comment by LegitSoulja** [comment]
Oh, @systemroot $sql->close()?

**Comment by LegitSoulja** [comment]
https://github.com/LegitSoulja/SlickInject/blob/master/lib/SlickInject.php

$_slickinject->close();

**Comment by LegitSoulja** [comment]
Or rename $_slickinject to $sql 😛

**Comment by systemroot** [comment]
was just a file which i was using before i forgot to remove it! http://imgur.com/a/tdq1w

**Comment by LegitSoulja** [comment]
@systemroot oh ok, it's because I never documented it. Just making sure :)

**Comment by LegitSoulja** [comment]
@systemroot In the Dev, SELECT has changed.

When you use select, an array of the rows will return. No need to do ->returnRows($.

I feel you however need to count rows, just simply make the 4th argument false for ex

$si->SELECT([], "table", array("id"=>1, false));

Using false, will return back the SQLResponse (w/ SQLObject). Store this response, or use a server so

$si->SELECT([], "table", array("id"=>1, false))->num_rows();

Or

$si->SELECT([], "table", array("id"=>1, false))->getResponce()->num_rows;

Hope you understand

**Comment by LegitSoulja** [comment]
returnRows still can be used if the 4th argument is false, BUT

returnRows is deprecated.
Use now getData()

**Comment by systemroot** [comment]
i was using it like
```php
$data = $_slickinject->SELECT([], "vms", array("id"=>1));
echo $data[0]['name']; 
```

**Comment by LegitSoulja** [comment]
Another Dev addition

When using WHERE array("id"=>1, "userid"=>666), it will return 

```sql
WHERE `id`=1 AND `userid`=666. 
```

It automatically adds AND if you don't specify. I'm working more and more on making my Parser smarter

**Comment by LegitSoulja** [comment]
@systemroot Okay, now things are officially done.

https://github.com/LegitSoulja/SlickInject/releases/tag/1.0

Master branch has been merged. If you have any future problems just let me know.

**Comment by systemroot** [comment]
@LegitSoulja no support for multi tables?
```php
$_slickinject->connect("localhost", "dopehost_bot_us", "dab", "dopehost_bot");

// update
$_slickinject->UPDATE('vms, vms_1, vms_2', array("name"=>"$name"), array("id"=>1));
```
output
```php
Error Table 'dopehost_bot.vms, vms_1, vms_2' doesn't exist
```

![](http://i.imgur.com/x1uYH5l.png)

**Comment by LegitSoulja** [comment]
@systemroot I never knew you can update 2 tables at once. 

Answer to your question is no. However, it can be implemented.

**Comment by LegitSoulja** [comment]
Actually, a quick fix.

Parser.php line 90 change
```php
        $z = str_replace("%s", "`" . ($table) . "`", $z);
```

To

```php
        $z = str_replace("%s", ($table), $z);
```

Be cautious not to use any operators as the table name.

**Comment by LegitSoulja** [comment]
And was array("name"=>"$name") a mistake?

Don't use variables as a string, instead, it should be

array("name"=>"(string)$name)

**Comment by systemroot** [comment]
it won't work :confused: .
i still can get what i want done.. just i was thinking to use a small line of code!

**Comment by LegitSoulja** [comment]
@systemroot that fix didn't work? How so? Also, please update SlickInject. Updating/Inserting data with a number, as of 0 doesn't work.

Somehow, in php (empty(0)) = true.
