### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by LegitSoulja** [LegitSoulja/SlickInject#6]
v2 changes & details

- Got rid of a-lot of bugs (work-arounds), in replace of re-wrote system.
- No longer using query/request but instead prepare and execute.
- Faster processing, shouldn't reflect any CPU/Overload notices. 
- Smarter
- Protection against reserved keywords & operators.

Using prepare/execute is more secure than having to escape strings to prevent SQL injections. 

Using prepare/execute should've been used in v1, but it was complicating and hard to get it working properly. However, I've managed to solve my issue, and will now be release this re-made version.

**Comment by LegitSoulja** [comment]
Dev: https://github.com/LegitSoulja/SlickInject/blob/v3/v3.php

**Comment by Slingou** [comment]
How do I use ths?

**Comment by LegitSoulja** [comment]
@Slingou the files in the lib folder must be loaded however you wish. 

Include files,

- SQLObject
- SlickInject
- Parser

**Comment by LegitSoulja** [comment]
Compile/Build tool now exists. If the build is outdated, manually obtain it here [Download](http://legitsoulja.info/SlickInject.php), [Build Status](http://legitsoulja.info/SlickInject.php?status)
